service: youtube-api
frameworkVersion: "3"

Provider: 
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

functions: 
  youtubeHelloFn:
    handler: hello.handler
    events:
      - httpApi:
          path: /hello
          method: get
  youtubeByeFn:
    handler: bye.handler
    events:
      - httpApi:
        path: /bye
        method: get
