service: youtube-api
frameworkVersion: "3"

provider: 
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions: 
  youtubeHelloFn:
    handler: hello.handler
    events:
      - httpApi:
          path: /hello
          method: get
  youtubeByeFn:
    handler: bye.handler
    events:
      - httpApi:
          path: /bye
          method: get
